---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Redmoon.
--- DateTime: 2021/9/13 15:31
---
require("Core")
print("start")
print("Test 1")
CS.LuaHelper.Test(function()
    print("Test 2")
end)
